// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initMobileLogger() =>
    RustLib.instance.api.crateMobileApiInitMobileLogger();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileVault>>
abstract class MobileVault implements RustOpaqueInterface {
  Future<List<MobileFileInfo>> listFiles();

  static Future<MobileVault> newInstance({
    required String path,
    required String password,
  }) => RustLib.instance.api.crateMobileApiMobileVaultNewInstance(
    path: path,
    password: password,
  );
}

/// Simplified file info for mobile UI
class MobileFileInfo {
  final String name;
  final BigInt size;
  final bool isDir;

  const MobileFileInfo({
    required this.name,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileFileInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isDir == other.isDir;
}
