// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';

export function CreateVault(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<vault.FileEntry>>;

export function OpenVault(arg1:string,arg2:string):Promise<void>;
