// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BiometricsDelete(arg1, arg2) {
  return window['go']['main']['App']['BiometricsDelete'](arg1, arg2);
}

export function BiometricsGet(arg1, arg2) {
  return window['go']['main']['App']['BiometricsGet'](arg1, arg2);
}

export function BiometricsStore(arg1, arg2, arg3) {
  return window['go']['main']['App']['BiometricsStore'](arg1, arg2, arg3);
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function GetVaultID(arg1) {
  return window['go']['main']['App']['GetVaultID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function OpenVault(arg1, arg2) {
  return window['go']['main']['App']['OpenVault'](arg1, arg2);
}
